/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package historia1.vistas;

import java.text.DateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

import historia1.negocio.SATarifa;
import historia1.negocio.TipoHabitacion;
import historia1.negocio.TransferTarifa;

/**
 *
 * @author alex
 */
public class GUIAltaTarifa2 extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private GUIAltaTarifa gui;
	private Date inicioTarifa;
	private Date finTarifa;
	private String habitacion, inicioTarifa_s, finTarifa_s;
	private DateFormat dateFormat;
	private TipoHabitacion habitacion_e;

	/**
	 * Creates new form GUIAltaTarifa2
	 */
	public GUIAltaTarifa2() {
		initComponents();
	}

	GUIAltaTarifa2(GUIAltaTarifa aThis) {
		// To change body of generated methods, choose Tools | Templates.
		gui = aThis;
		dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		labelFechaInicio = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jPanel8 = new javax.swing.JPanel();
		labelFechaFin = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel13 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jPanel9 = new javax.swing.JPanel();
		labelDeTipoHabitacion = new javax.swing.JLabel();
		jPanel10 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jPanel11 = new javax.swing.JPanel();
		jTextPrecio = new javax.swing.JTextField();
		jPanel12 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jPanel14 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("Pulsa aceptar cuando hayas introducido la tarifa");
		setBackground(new java.awt.Color(204, 255, 255));
		getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

		jPanel1.setBackground(new java.awt.Color(204, 255, 255));
		jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

		jPanel4.setBackground(new java.awt.Color(204, 255, 255));
		jPanel4.setPreferredSize(new java.awt.Dimension(50, 98));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 50, Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 75, Short.MAX_VALUE));

		jPanel1.add(jPanel4);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Desde la fecha ");
		jPanel1.add(jLabel1);

		jPanel5.setBackground(new java.awt.Color(204, 255, 255));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 3, Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 75, Short.MAX_VALUE));

		jPanel1.add(jPanel5);

		labelFechaInicio.setText(inicioTarifa_s);
		jPanel1.add(labelFechaInicio);

		jPanel7.setBackground(new java.awt.Color(204, 255, 255));

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 3, Short.MAX_VALUE));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 75, Short.MAX_VALUE));

		jPanel1.add(jPanel7);

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel5.setText("hasta la fecha");
		jPanel1.add(jLabel5);

		jPanel8.setBackground(new java.awt.Color(204, 255, 255));

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 3, Short.MAX_VALUE));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 75, Short.MAX_VALUE));

		jPanel1.add(jPanel8);

		labelFechaFin.setText(finTarifa_s);
		jPanel1.add(labelFechaFin);

		jPanel6.setBackground(new java.awt.Color(204, 255, 255));

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 75, Short.MAX_VALUE));

		jPanel1.add(jPanel6);

		getContentPane().add(jPanel1);

		jPanel2.setBackground(new java.awt.Color(204, 255, 255));
		jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

		jPanel13.setBackground(new java.awt.Color(204, 255, 255));
		jPanel13.setPreferredSize(new java.awt.Dimension(50, 195));

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout.setHorizontalGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 21, Short.MAX_VALUE));
		jPanel13Layout.setVerticalGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 146, Short.MAX_VALUE));

		jPanel2.add(jPanel13);

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("Una habitacion");
		jPanel2.add(jLabel2);

		jPanel9.setBackground(new java.awt.Color(204, 255, 255));
		jPanel9.setPreferredSize(new java.awt.Dimension(20, 96));

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 8, Short.MAX_VALUE));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 146, Short.MAX_VALUE));

		jPanel2.add(jPanel9);

		labelDeTipoHabitacion.setText("jLabel3");
		jPanel2.add(labelDeTipoHabitacion);

		jPanel10.setBackground(new java.awt.Color(204, 255, 255));
		jPanel10.setPreferredSize(new java.awt.Dimension(25, 195));

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 10, Short.MAX_VALUE));
		jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 146, Short.MAX_VALUE));

		jPanel2.add(jPanel10);

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setText("tendra un precio de");
		jPanel2.add(jLabel4);

		jPanel11.setBackground(new java.awt.Color(204, 255, 255));
		jPanel11.setPreferredSize(new java.awt.Dimension(15, 195));

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 6, Short.MAX_VALUE));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 146, Short.MAX_VALUE));

		jPanel2.add(jPanel11);

		jTextPrecio.setText(" ");
		jTextPrecio.setPreferredSize(new java.awt.Dimension(25, 25));
		jTextPrecio.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextPrecioActionPerformed(evt);
			}
		});
		jPanel2.add(jTextPrecio);

		jPanel12.setBackground(new java.awt.Color(204, 255, 255));
		jPanel12.setPreferredSize(new java.awt.Dimension(20, 139));

		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout.setHorizontalGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 8, Short.MAX_VALUE));
		jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 146, Short.MAX_VALUE));

		jPanel2.add(jPanel12);

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel6.setText("euros por noche");
		jPanel2.add(jLabel6);

		jPanel14.setBackground(new java.awt.Color(204, 255, 255));
		jPanel14.setPreferredSize(new java.awt.Dimension(20, 146));

		javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
		jPanel14.setLayout(jPanel14Layout);
		jPanel14Layout.setHorizontalGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 8, Short.MAX_VALUE));
		jPanel14Layout.setVerticalGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 146, Short.MAX_VALUE));

		jPanel2.add(jPanel14);

		getContentPane().add(jPanel2);

		jPanel3.setBackground(new java.awt.Color(204, 255, 255));
		jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

		jButton1.setBackground(new java.awt.Color(204, 255, 255));
		jButton1.setForeground(new java.awt.Color(255, 0, 0));
		jButton1.setText("Aceptar");
		jButton1.setPreferredSize(new java.awt.Dimension(200, 30));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel3.add(jButton1);

		getContentPane().add(jPanel3);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextPrecioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextPrecioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextPrecioActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:

		double precio;
		boolean valido = true;

		try {
			precio = Double.parseDouble(jTextPrecio.getText());
		} catch (Exception e) {
			valido = false;
			JOptionPane.showMessageDialog(null, "Datos introducidos incorrectos");
			this.setVisible(false);
			gui.setVisible(true);
		}

		if (valido) {

			try {
				precio = Double.parseDouble(jTextPrecio.getText());
				setVisible(false);
				new SATarifa().alta(new TransferTarifa(inicioTarifa, finTarifa, habitacion_e.ordinal() + 1, precio));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e.getMessage());
				this.setVisible(false);
			} finally {
				gui.setVisible(true);
			}

		}

	}// GEN-LAST:event_jButton1ActionPerformed

	void showInfo(Date inicioTarifa, Date finTarifa, TipoHabitacion hab) {
		this.inicioTarifa = inicioTarifa;
		this.finTarifa = finTarifa;
		this.habitacion = hab.name();
		habitacion_e = hab;
		inicioTarifa_s = dateFormat.format(inicioTarifa);
		finTarifa_s = dateFormat.format(finTarifa);
		labelFechaInicio.setText(inicioTarifa_s);
		labelFechaFin.setText(finTarifa_s);
		labelDeTipoHabitacion.setText(habitacion);
		setVisible(true);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JTextField jTextPrecio;
	private javax.swing.JLabel labelDeTipoHabitacion;
	private javax.swing.JLabel labelFechaFin;
	private javax.swing.JLabel labelFechaInicio;
	// End of variables declaration//GEN-END:variables
}
