/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package launcher;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import carlos_historias_4_5_6_7.IntroducirUsuarioLimpiezaFrame;

/**
 *
 * @author alex
 */
public class ActoresFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form Actores
	 */
	public ActoresFrame() {
		initComponents();
		setSize(655, 200);
		setPreferredSize(new Dimension(655, 200));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton6 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		bPersonalLimpieza = new javax.swing.JButton();
		bRestaurante = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		//jButton4 = new javax.swing.JButton();
		//jButton5 = new javax.swing.JButton();

		jButton6.setText("jButton6");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Bienvenido");
		setBackground(new java.awt.Color(153, 255, 255));
		setMaximumSize(new java.awt.Dimension(365, 150));
		setMinimumSize(new java.awt.Dimension(365, 150));
		setPreferredSize(new java.awt.Dimension(365, 150));
		setResizable(false);
		getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

		jPanel4.setBackground(new java.awt.Color(204, 255, 255));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(51, 51, 255));
		jLabel2.setText("Acceder al sistema como");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
						.addContainerGap(244, Short.MAX_VALUE).addComponent(jLabel2).addGap(192, 192, 192)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel4Layout.createSequentialGroup().addGap(0, 18, Short.MAX_VALUE).addComponent(jLabel2)));

		getContentPane().add(jPanel4);

		jPanel1.setBackground(new java.awt.Color(204, 255, 255));
		jPanel1.setPreferredSize(new java.awt.Dimension(772, 100));
		jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

		jPanel2.setBackground(new java.awt.Color(204, 255, 255));
		jPanel2.setPreferredSize(new java.awt.Dimension(100, 289));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 11, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 118, Short.MAX_VALUE));

		jPanel1.add(jPanel2);

		jButton1.setText("Gerente");
		jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1);

		jButton2.setText("Recepcionista");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton2);

		bPersonalLimpieza.setText("Personal de Limpieza");
		bPersonalLimpieza.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bPersonalLimpiezaActionPerformed(evt);
			}
		});
		jPanel1.add(bPersonalLimpieza);

		bRestaurante.setText("Encargado del Restaurante");
		bRestaurante.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bRestauranteActionPerformed(evt);
			}
		});
		jPanel1.add(bRestaurante);

		jButton3.setText("Administracion");
		jButton3.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				codigo.GUI.main(null);
			}
		});
		jPanel1.add(jButton3);

		getContentPane().add(jPanel1);

		jPanel5.setBackground(new java.awt.Color(204, 255, 255));
		jPanel5.setPreferredSize(new java.awt.Dimension(656, 50));

		//jButton4.setText("Recepcionista: Check in");
		//jButton4.addActionListener(new ActionListener() {

//			@Override
//			public void actionPerformed(ActionEvent e) {
//				// TODO Auto-generated method stub
//				recep_52_alejandro_checkin.GUI.main(null);
//			}
//		});
		//jButton5.setText("Recepcionista: Check out");
		//jButton5.setActionCommand("Recepcionista: Check out");
		//jButton5.addActionListener(new ActionListener() {
//
//			@Override
//			public void actionPerformed(ActionEvent e) {
//				// TODO Auto-generated method stub
//				recep_50_alejandro_checkout.GUI.main(null);
//			}
//		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
//		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(jPanel5Layout.createSequentialGroup().addGap(129, 129, 129).addComponent(jButton4)
//						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
//						.addComponent(jButton5).addGap(112, 112, 112)));
//		jPanel5Layout
//				.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//						.addGroup(jPanel5Layout.createSequentialGroup()
//								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//										.addComponent(jButton4).addComponent(jButton5))
//								.addGap(0, 45, Short.MAX_VALUE)));

		//getContentPane().add(jPanel5);

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		dispose();
		GerenteFrame.main(null);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		dispose();
		RecepcionistaFrame.main(null);

		// RecepcionistaFrame pr = new RecepcionistaFrame();
		// pr.setLocationRelativeTo(this); //Centra la ventana en funcion a la
		// ventana anterior
		// pr.setVisible(true);
	}

	private void bPersonalLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		IntroducirUsuarioLimpiezaFrame.main(null);
	}

	private void bRestauranteActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		EncargadoRestauranteFrame.main(null);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ActoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ActoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ActoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ActoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new ActoresFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton bPersonalLimpieza;
	private javax.swing.JButton bRestaurante;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	// End of variables declaration
}
