/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package launcher;

import carlos_historias_4_5_6_7.DarAltaAlimentosYBebidasDialog;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import jdbc.BD;

/**
 *
 * @author carlos
 */
public class EncargadoRestauranteFrame extends javax.swing.JFrame {

    /**
     * Creates new form EncargadoRestauranteFrame
     */
    public EncargadoRestauranteFrame() {
        initComponents();
        darAltaAlimentosYBebidasDialog = new DarAltaAlimentosYBebidasDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bDarAltaAlimentosBebidas = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bDarAltaAlimentosBebidas.setText("Dar de alta alimentos y bebidas");
        bDarAltaAlimentosBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDarAltaAlimentosBebidasActionPerformed(evt);
            }
        });

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bDarAltaAlimentosBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bDarAltaAlimentosBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDarAltaAlimentosBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDarAltaAlimentosBebidasActionPerformed
        try{
            //Lanzamos el diálogo
            if(darAltaAlimentosYBebidasDialog.showDialog()){
                //Si se ha pulsado aceptar tenemos que guardar toda la info en la BD
            	String nombre = darAltaAlimentosYBebidasDialog.getNombre();
                String tipo = darAltaAlimentosYBebidasDialog.getTipo();
                Map<String,Double> lugares_precios = new HashMap<>();
                LocalDate fechaAlta = darAltaAlimentosYBebidasDialog.getFechaAlta();
                int diaAlta = fechaAlta.getDayOfMonth();
                int mesAlta = fechaAlta.getMonthValue();
                int anioAlta = fechaAlta.getYear();
                
                if(darAltaAlimentosYBebidasDialog.isLugarRestaurante())
                    lugares_precios.put("restaurante", darAltaAlimentosYBebidasDialog.getPrecioRestaurante());
                if(darAltaAlimentosYBebidasDialog.isLugarCafeteria())
                    lugares_precios.put("cafeteria", darAltaAlimentosYBebidasDialog.getPrecioCafeteria());
                if(darAltaAlimentosYBebidasDialog.isLugarMinibar())
                    lugares_precios.put("minibar", darAltaAlimentosYBebidasDialog.getPrecioMinibar());
                
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            	
                //Traza
                System.out.println("\nAlimento:");
                System.out.println("Nombre: "+nombre);
                System.out.println("Tipo: "+tipo);
                System.out.println("Fecha Alta: "+dtf.format(fechaAlta));
                for(Map.Entry<String,Double> par : lugares_precios.entrySet()){
                    System.out.println("Lugar: "+par.getKey()+" Precio: "+par.getValue());
                }
                
                //Guardamos la info en la BD (hay que restarle 1 al mes porque los meses en java.sql empiezan en 0
    		boolean creado = BD.crearAlimento(nombre, tipo, new java.sql.Date(anioAlta,mesAlta-1,diaAlta), lugares_precios);
                if(creado)
                    System.out.println("Se ha creado el alimento");
                else System.out.println("Error creando el alimento");
            }
        } catch(Exception e){e.printStackTrace();}
        
    }//GEN-LAST:event_bDarAltaAlimentosBebidasActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        dispose();
        ActoresFrame.main(null);
    }//GEN-LAST:event_bAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncargadoRestauranteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncargadoRestauranteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncargadoRestauranteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncargadoRestauranteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncargadoRestauranteFrame().setVisible(true);
            }
        });
    }

    private DarAltaAlimentosYBebidasDialog darAltaAlimentosYBebidasDialog;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bDarAltaAlimentosBebidas;
    // End of variables declaration//GEN-END:variables
}
