/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo.com.toedter.micalendar;

import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author alex
 */
public class AnadirHorarioFrame extends javax.swing.JFrame {

	private JCalendar mj;
	public int id;

	/**
	 * Creates new form AnadirHorarioFrame
	 * 
	 * @param d
	 */
	public void setDate(Date d) {
		
		SimpleDateFormat t = new SimpleDateFormat("dd/MM/yy");
		labelDEldia.setText(t.format(d));
		GregorianCalendar gc = new GregorianCalendar();
		gc.setTime(d);
		id = gc.get(GregorianCalendar.DAY_OF_WEEK);
		this.d = d;
	}

	public AnadirHorarioFrame(JCalendar jCalendar) {
		// TODO Auto-generated constructor stub
	initComponents();
	firstHour = -1;
		lastHour = -1;
		first2Hour = -1;
		last2Hour = -1;
		horasTotales = 0;
		js = true;
		this.mj = jCalendar;
		jsEnabled(js);
		jpEnabled(!js);
		setVisible(false);	
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
	//	jButtonAceptar.setEnabled(false);
		jButtonAplicarParaTodos.setEnabled(false);
		jButtonAplicarParaTodos.setVisible(false);
	}

	public Date d;

	private boolean js;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSpinnerJP2 = new javax.swing.JSpinner();
		jSpinnerJP2.addChangeListener(new ChangeListener() {
			
			@Override
			public void stateChanged(ChangeEvent e) {
				// TODO Auto-generated method stub
				update();
			}
		});
		jSpinnerJP1 = new javax.swing.JSpinner();
		jSpinnerJP1.addChangeListener(new ChangeListener() {
			
			@Override
			public void stateChanged(ChangeEvent e) {
				// TODO Auto-generated method stub
				update();
			}
		});
		
		jSpinnerJS2 = new javax.swing.JSpinner();
		jSpinnerJS2.addChangeListener(new ChangeListener() {
			
			@Override
			public void stateChanged(ChangeEvent e) {
				// TODO Auto-generated method stub
				update();
			}
		});
		
		
			jSpinnerJP4 = new javax.swing.JSpinner();
			jSpinnerJP4.addChangeListener(new ChangeListener() {
				
				@Override
				public void stateChanged(ChangeEvent e) {
					// TODO Auto-generated method stub
					update();
				}
			});
		
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		labelDEldia = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jButtonAceptar = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		jSpinnerJP5 = new javax.swing.JSpinner();
		jSpinnerJP5.addChangeListener(new ChangeListener() {
			
			@Override
			public void stateChanged(ChangeEvent e) {
				// TODO Auto-generated method stub
				update();
			}
		});
		jSpinnerJS1 = new javax.swing.JSpinner();
		jSpinnerJS1.addChangeListener(new ChangeListener() {
			
			@Override
			public void stateChanged(ChangeEvent e) {
				// TODO Auto-generated method stub
				update();
			}
		});
		jLabel10 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jButtonCambiar = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabelHorasTotales = new javax.swing.JLabel();
		jButtonAplicarParaTodos = new javax.swing.JButton();
		jLabelPartida = new javax.swing.JLabel();
		jLabelSeguida = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jSpinnerJP2.setModel(new javax.swing.SpinnerNumberModel(12, 0, 16, 1));

		jSpinnerJP1.setModel(new javax.swing.SpinnerNumberModel(8, 0, 16, 1));

		jSpinnerJS2.setModel(new javax.swing.SpinnerNumberModel(16, 0, 24, 1));

		jLabel1.setText("Desde");

		jLabel2.setText("Descanso");

		jSpinnerJP4.setModel(new javax.swing.SpinnerNumberModel(16, 16, 24, 1));

		jLabel3.setText("Hasta");

		jLabel4.setText("Dia");

		labelDEldia.setText("jLabel");

		jLabel6.setText("Desde");

		jLabel7.setText("Hasta");

		jButtonAceptar.setText("Aceptar");
		jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAceptarActionPerformed(evt);
			}
		});

		jLabel9.setText("Has selecionado        --------------------");

		jSpinnerJP5.setModel(new javax.swing.SpinnerNumberModel(20, 16, 24, 1));

		jSpinnerJS1.setModel(new javax.swing.SpinnerNumberModel(8, 0, 24, 1));

		jLabel10.setText("horas");

		jLabel8.setForeground(new java.awt.Color(255, 0, 0));

		jButtonCambiar.setText("Cambiar jornada");
		jButtonCambiar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCambiarActionPerformed(evt);
			}
		});

		jLabel12.setText("Desde");

		jLabel13.setText("Hasta");

		jLabelHorasTotales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabelHorasTotales.setText("8");

		jButtonAplicarParaTodos.setText("Actualizar");
		jButtonAplicarParaTodos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aplicarParaTodos(evt);
			}
		});

		jLabelPartida.setText("Jornada partida");

		jLabelSeguida.setText("Jornada seguida");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(39, 39, 39)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
										jLabel7).addComponent(jLabel6))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel8).addComponent(jLabel9))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jLabelHorasTotales,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE,
																39, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jButtonAceptar)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGap(0, 0, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup().addComponent(jLabel4)
																.addGap(26, 26, 26).addComponent(labelDEldia)
																.addGap(114, 114, 114))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButtonCambiar).addComponent(jButtonAplicarParaTodos))))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
														.addComponent(jLabelSeguida))
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jSpinnerJP4,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 60,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jSpinnerJP5,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 60,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(0, 0, Short.MAX_VALUE))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
																.createSequentialGroup().addGap(0, 154, Short.MAX_VALUE)
																.addGroup(layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel1).addComponent(jLabel13))))
														.addGap(18, 18, 18)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jSpinnerJS1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 60,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jSpinnerJS2,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 60,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(11, 11, 11)))
						.addGap(75, 75, 75))
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabelPartida)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(37, 37, 37)
										.addComponent(jLabel12).addGap(18, 18, 18)
										.addComponent(jSpinnerJP1, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(39, 39, 39)
												.addComponent(jLabel3).addGap(18, 18, 18)
												.addComponent(jSpinnerJP2, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												layout.createSequentialGroup().addGap(46, 46, 46).addComponent(jLabel2)
														.addGap(14, 14, 14)))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(labelDEldia))
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelPartida).addComponent(jLabelSeguida))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jSpinnerJP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1)
								.addComponent(jSpinnerJS1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel12))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(jSpinnerJP2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSpinnerJS2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel13))
						.addGap(18, 18, 18)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jSpinnerJP4, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6).addComponent(jButtonCambiar))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel7).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jSpinnerJP5, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButtonAplicarParaTodos)))
						.addGap(38, 38, 38)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel10).addComponent(jLabelHorasTotales))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8).addComponent(jButtonAceptar))
						.addGap(23, 23, 23)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAceptarActionPerformed
		// TODO add your handling code here:
		update();

		setVisible(false);
	}// GEN-LAST:event_jButtonAceptarActionPerformed

	private void jButtonCambiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonLimpiarActionPerformed
		// TODO add your handling code here:
		js = !js;
		jsEnabled(js);
		jpEnabled(!js);
		update();
	}// GEN-LAST:event_jButtonLimpiarActionPerformed

	public int horasTotales;

	private void aplicarParaTodos(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	public int lastHour, firstHour;
	public Integer last2Hour;
	public Integer first2Hour;
	private boolean error;

	private void update() {
	
		if (js) {

			horasTotales = (Integer) jSpinnerJS2.getValue() - (Integer) jSpinnerJS1.getValue();
			jLabelHorasTotales.setText(String.valueOf(horasTotales));
			lastHour = (Integer) jSpinnerJS2.getValue();
			firstHour = (Integer) jSpinnerJS1.getValue();
		} else {

			horasTotales = ((Integer) jSpinnerJP5.getValue() - (Integer) jSpinnerJP4.getValue())
					+ ((Integer) jSpinnerJP2.getValue() - (Integer) jSpinnerJP1.getValue());
			jLabelHorasTotales.setText(String.valueOf(horasTotales));

			lastHour = (Integer) jSpinnerJP5.getValue();
			firstHour = (Integer) jSpinnerJP1.getValue();
			last2Hour = (Integer) jSpinnerJP2.getValue();
			first2Hour = (Integer) jSpinnerJP4.getValue();
		}

		for (int i = 0; i < mj.horarios.size(); i++) {
			if (mj.horarios != null) {

				System.out.println("                                                 id  " + mj.horarios.get(i).id);
				System.out.println(
						"                                                 fh  " + mj.horarios.get(i).firstHour);
				System.out
						.println("                                                 lh  " + mj.horarios.get(i).lastHour);
			}

		}

		switch (id) {
		case 1:
			if (mj.horarios.get(5).lastHour != -1 && mj.horarios.get(5).lastHour - firstHour > 12) {
				jLabel8.setText("No hay 12 horas de descanso");
				jButtonAceptar.setEnabled(false);
				error = true;
			} else {
				jLabel8.setText(null);
				jButtonAceptar.setEnabled(true);
				error = false;
			}
			break;

		case 2:
			if (mj.horarios.get(0).firstHour != -1 && lastHour - mj.horarios.get(0).firstHour > 12) {
				jLabel8.setText("No hay 12 horas de descanso");
				jButtonAceptar.setEnabled(false);
				error = true;
			} else {
				jLabel8.setText(null);
				jButtonAceptar.setEnabled(true);
				error = false;
			}
			break;

		default:
			if (((mj.horarios.get(id - 3).lastHour - firstHour > 12) && (mj.horarios.get(id - 3).lastHour != -1))
					|| ((mj.horarios.get(id - 1).firstHour != -1) && (lastHour - mj.horarios.get(id - 1).firstHour > 12))) {
				jLabel8.setText("No hay 12 horas de descanso");
				jButtonAceptar.setEnabled(false);
				error = true;
			} else {
				jLabel8.setText(null);
				jButtonAceptar.setEnabled(true);
				error = false;
			}
			break;
		}

		if (horasTotales > 8) {
			jLabel8.setText("Hay mas de 8 horas");
			jButtonAceptar.setEnabled(false);
		} else {
			if (!error) {
				jLabel8.setText(null);
				jButtonAceptar.setEnabled(true);
			}
		}

	}

	private void jsEnabled(boolean b) {
		jLabelSeguida.setEnabled(b);
		jSpinnerJS1.setEnabled(b);
		jSpinnerJS2.setEnabled(b);
		jLabelSeguida.setVisible(b);
		jSpinnerJS1.setVisible(b);
		jSpinnerJS2.setVisible(b);
		jLabel1.setVisible(b);
		jLabel13.setVisible(b);
	}

	private void jpEnabled(boolean b) {
		jLabelPartida.setEnabled(b);
		jSpinnerJP1.setEnabled(b);
		jSpinnerJP2.setEnabled(b);
		jSpinnerJP5.setEnabled(b);
		jSpinnerJP4.setEnabled(b);
		jLabelPartida.setVisible(b);
		jSpinnerJP1.setVisible(b);
		jSpinnerJP2.setVisible(b);
		jSpinnerJP5.setVisible(b);
		jSpinnerJP4.setVisible(b);
		jLabel12.setVisible(b);
		jLabel3.setVisible(b);
		jLabel6.setVisible(b);
		jLabel2.setVisible(b);
		jLabel7.setVisible(b);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAplicarParaTodos;
	private javax.swing.JLabel jLabelPartida;
	private javax.swing.JLabel jLabelSeguida;
	private javax.swing.JButton jButtonAceptar;
	private javax.swing.JButton jButtonCambiar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabelHorasTotales;
	private javax.swing.JSpinner jSpinnerJP1;
	private javax.swing.JSpinner jSpinnerJP2;
	private javax.swing.JSpinner jSpinnerJP4;
	private javax.swing.JSpinner jSpinnerJP5;
	private javax.swing.JSpinner jSpinnerJS1;
	private javax.swing.JSpinner jSpinnerJS2;
	private javax.swing.JLabel labelDEldia;
	// End of variables declaration//GEN-END:variables

}
