/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recep_52_alejandro_checkin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alex
 */
public class RegistrarAcompanantes extends javax.swing.JFrame implements ActionListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	static int i = 0;
	static Integer n;

	List<DatosAcompanante> lista = new ArrayList<>();

	private String id;

	/**
	 * Creates new form RegistrarAcompanantes
	 */
	public RegistrarAcompanantes() {
		initComponents();
		jButton1.addActionListener(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jSpinner1 = new javax.swing.JSpinner();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setText("Introduce el numero de acompanates");

		jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

		jButton1.setText("Registrar datos de cada acompanante");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
										.addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
						.addComponent(jButton1).addGap(22, 22, 22)));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		RegistrarAcompanantes r = new RegistrarAcompanantes();
		// r.id = args[0]; //
		r.setVisible(true);
		;
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JSpinner jSpinner1;
	// End of variables declaration

	@Override
	public void actionPerformed(ActionEvent e) {
		n = (Integer) jSpinner1.getValue();
		for (int i = 0; i < n; i++)
			lista.add(new DatosAcompanante(this));

		setVisible(false);

		if (n != 0)
			lista.get(0).setVisible(true);
		else
			JOptionPane.showMessageDialog(new JFrame(),
					"Ya se han dado de alta todos los acampanantes\nCheck in finalizado");
	}

	public void next() {
		i++;
		if (i == n) {
			lista.get(i - 1).setVisible(false);
			JOptionPane.showMessageDialog(new JFrame(),
					"Ya se han dado de alta todos los acampanantes\nCheck in finalizado");
		} else {
			lista.get(i - 1).setVisible(false);
			lista.get(i).setVisible(true);
		}
	}

	public int getIdReserva() {
		// TODO Auto-generated method stub
		return Integer.parseInt(id);
	}
}
